version: '3.8'

services:
    # Application Service
    app:
        container_name: app
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        working_dir: /app
