export const API_ENDPOINTS = {
    AUTH: {
        SIGNUP: '/auth/signup',
        SIGNIN: '/auth/signin',
        GOOGLE_SIGN_IN: '/auth/google-signin',
        FACEBOOK_SIGN_IN: '/auth/facebook-signin',
        GET_USER: '/auth/get-user',
        VERIFY_OTP: '/auth/otp-verify',
        LOG_OUT: '/auth/logout',
        FORGOT_PASSWORD: '/auth/forgotPassword',
        RESET_PASSWORD: '/auth/reset-password',
        VERIFY_ACCOUNT: '/auth/verify-account',
        RESEND_EMAIL: '/auth/resend-email'
    },
    USER: {
        PROFILE_IMAGE: '/user/upload-avatar/:id',
        UPDATE_PROFILE: '/user/:id',
        CHANGE_PASSWORD: '/user/change-password'
    },
    COUNTRY: '/country',
    DEGREE: '/degree',
    DISCIPLINE: '/discipline',
    DISCIPLINE_COUNT: '/discipline/count',
    DISCIPLINE_PAGINATED: '/discipline/paginated',
    SCHOLARSHIP: '/scholarship',
    SCHOLARSHIP_BY_ID: '/scholarship/:id',
    COURSE_DEGREE_ID: '/course/degree',
    COURSE_By_SPECIALIZATION_ID: '/course/specializations/:id',
    COURSE_INSTITUTE_ID: '/course/institute',
    DEGREES_BY_INSTITUTE_ID: '/course/institute/degree/:id',
    COURSE_SEARCH: '/course/filter',
    COURSE_BY_ID: '/course/:id',
    SCHOLARSHIP_SEARCH: '/scholarship/filter',
    FAVORITE: '/favorite',
    FAVORITE_DELETE: '/favorite/delete',
    USER_FAVORITES: '/favorite/user?type=:type',
    SPECIALIZATION: '/specialization',
    INSTITUTE: '/institute',
    INSTITUTE_BY_ID: '/institute/:id',
    INSTITUTE_WITH_COUNTRY_ID: '/institute/country/:id',
    DEGREE_WITH_INSTITUTE_ID: '/institute/degrees/:id',
    DEGREE_LEVELS_WITH_DISCIPLINE_ID: '/discipline/degree-levels/:id',
    COURSES_WITH_DEGREE: '/course/compare/:degreeId/:instituteId',
    CONTACT: '/contact',
    BLOGS: '/blogs',
    SINGLE_BLOG: '/blogs/:id',
    APPLY: '/apply',
    GET_APPLY_BY_ID: '/apply/:id',
    APPLY_USER: '/apply/user',
    GEO_IP: '/geoip',
    FETCH_RATES:
        // 'https://fxds-public-exchange-rates-api.oanda.com/cc-api/currencies?base=PKR&quote=${code}&data_type=general_currency_pair&start_date=${pDate}&end_date=${cDate}',
        '/currency_rate/find?from_code=PKR&to_code=${code}&start_date=${pDate}&end_date=${cDate}',
    FETCH_ALL_RATES: '/currency_rate?code=${code}&amount=${amount}',
    FILE_S3_UPLOAD: '/file/s3-upload',
    APPLY_DOCUMENTS: '/apply',
    EVENTS: '/event',
    FILE_UPLOAD: '/file/s3-upload',
    FILE_DELETE: '/file/s3-delete',
    GET_SCHOLARSHIP_BY_DEGREE: '/course/degree/specializations/:id',
    MESSAGE: '/message'
};
