export const API_ENDPOINTS = {
    AUTH: {
        SIGNUP: '/auth/signup',
        SIGNIN: '/auth/signin',
        GOOGLE_SIGN_IN: '/auth/google-signin',
        GET_USER: '/auth/get-user',
        VERIFY_OTP: '/auth/otp-verify',
        LOG_OUT: '/auth/logout',
        FORGOT_PASSWORD: '/auth/forgotPassword',
        RESET_PASSWORD: '/auth/reset-password',
        VERIFY_ACCOUNT: '/auth/verify-account'
    },
    USER: {
        PROFILE_IMAGE: '/user/upload-avatar/:id',
        UPDATE_PROFILE: '/user/:id',
        CHANGE_PASSWORD: '/user/change-password'
    },
    COUNTRY: '/country',
    DEGREE: '/degree',
    DISCIPLINE: '/discipline',
    DISCIPLINE_PAGINATED: '/discipline/paginated',
    SCHOLARSHIP: '/scholarship',
    SCHOLARSHIP_BY_ID: '/scholarship/:id',
    COURSE_DEGREE_ID: '/course/degree',
    COURSE_SEARCH: '/course/filter',
    COURSE_BY_ID: '/course/:id',
    SCHOLARSHIP_SEARCH: '/scholarship/filter',
    FAVORITE: '/favorite',
    FAVORITE_DELETE: '/favorite/delete',
    USER_FAVORITES: '/favorite/user?type=:type',
    SPECIALIZATION: '/specialization',
    INSTITUTE: '/institute',
    INSTITUTE_WITH_COUNTRY_ID: '/institute/country/:id',
    DISCIPLINES_WITH_INSTITUTE_ID: '/institute/disciplines/:id',
    DEGREE_LEVELS_WITH_DISCIPLINE_ID: '/discipline/degree-levels/:id',
    COURSES_WITH_DEGREE: '/course/compare/:degreeId/:instituteId',
    CONTACT: '/contact',
    BLOGS: '/blogs',
    SINGLE_BLOG: '/blogs/:id',
    APPLY: '/apply',
    APPLY_USER: '/apply/user'
};
