export const ROUTES = {
    HOMEPAGE: '/',
    SIGN_IN: '/signIn',
    SIGN_UP: '/signUp',
    COMPARE: '/compare',
    APPLY: '/apply',
    FILTER_COURSE: '/filter/course',
    COURSE: '/course/:title',
    FILTER_SCHOLARSHIP: '/filter/scholarship',
    SCHOLARSHIP: '/scholarship/:title',
    PROFILE: '/profile',
    COUNTRY: '/countries',
    FIELDS: '/categories',
    BLOGS: '/blogs',
    BLOGS_DETAIL: '/blogs/:id',
    INSTITUTES: '/institutes',
    INSTITUTES_DETAIL: '/institutes/:title',
    ABOUT_US: '/aboutUs',
    CONTACT_US: '/contactUs',
    FAQ: '/faq',
    PRIVACY_POLICY: '/privacyPolicy',
    TERMS_CONDITION: '/termsCondition',
    FAVORITES: '/profile?tab=Favourite&tab2=Institutes',
    APPLIES: '/profile?tab=Profile&tab2=My+Applications',
    APPLIES_DETAIL: '/profile/application/:id',
    FILE_SUBMIT: '/profile/application/file-submit',
    CONSOLID_MARKSHEET: '/profile/application/consolid-marksheet'
};
